debug:
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.project.boardproject : debug
    org.springframework.web.servlet : debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


spring:
  datasource:
    driver-class-name: org.h2.Driver
  #    url: jdbc:mysql://localhost:3306/board
#    username : summer
#    password : 1234
#    driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:h2:mem:testdb
  username: sa
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      show-sql: true
      open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
  sql.init.mode : always